#include "pin_config_h.h"

void PIN_Config_Init(void)
{
	// Status Light
	GPIO_Init(STATUS_LED_PORT, STATUS_LED_PIN, GPIO_MODE_OUTPUT, GPIO_OTYPE_PP, GPIO_SPEED_MEDIUM, GPIO_NOPUPD);
	
	// Motor PWM
	GPIO_Init(PWM_PORT, PWM_PIN, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_SPEED_MEDIUM, GPIO_NOPUPD);
	GPIO_Set_AF(PWM_PORT, PWM_PIN, GPIO_AF1);
	
	TIM_PWM_Init(PWM_TIMER, PWM_PSC, PWM_ARR);
	TIM_PWM_Enable_Channel(PWM_TIMER, PWM_CHANNEL);
	TIM_PWM_Set_Duty(PWM_TIMER, PWM_CHANNEL, 999);
	TIM_Start(PWM_TIMER);
	
	// Motor Directions
	GPIO_Init(DIR_PORT, DIR1_PIN, GPIO_MODE_OUTPUT, GPIO_OTYPE_PP, GPIO_SPEED_MEDIUM, GPIO_NOPUPD);
	GPIO_Init(DIR_PORT, DIR2_PIN, GPIO_MODE_OUTPUT, GPIO_OTYPE_PP, GPIO_SPEED_MEDIUM, GPIO_NOPUPD);
	GPIO_Reset_Pin(DIR_PORT, DIR1_PIN);
	GPIO_Reset_Pin(DIR_PORT, DIR2_PIN); 
	
}
